// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness/test/auth/register/domain/usecases/register_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness/core/common/result.dart' as _i4;
import 'package:super_fitness/features/auth/register/data/models/request/register_request.dart'
    as _i6;
import 'package:super_fitness/features/auth/register/domain/models/register_response_entity.dart'
    as _i5;
import 'package:super_fitness/features/auth/register/domain/repos/register_repo.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegisterRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterRepo extends _i1.Mock implements _i2.RegisterRepo {
  MockRegisterRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.RegisterResponseEntity?>> register(
          _i6.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.RegisterResponseEntity?>>.value(
            _i7.dummyValue<_i4.Result<_i5.RegisterResponseEntity?>>(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.RegisterResponseEntity?>>);
}
