// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness/test/auth/edit_profile/presentation/edit_profile_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:super_fitness/core/common/result.dart' as _i5;
import 'package:super_fitness/core/local/providers/user_provider.dart' as _i11;
import 'package:super_fitness/features/auth/domain/models/user.dart' as _i12;
import 'package:super_fitness/features/edit_profile/data/models/request/edit_profile_request.dart'
    as _i7;
import 'package:super_fitness/features/edit_profile/data/models/request/uplaod_image_request.dart'
    as _i10;
import 'package:super_fitness/features/edit_profile/data/models/response/edit_profile_response/upload_image_response.dart'
    as _i9;
import 'package:super_fitness/features/edit_profile/domain/entity/edit_profile_entity.dart'
    as _i6;
import 'package:super_fitness/features/edit_profile/domain/repos/edit_profile_repo.dart'
    as _i2;
import 'package:super_fitness/features/edit_profile/domain/use_cases/edit_profile_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEditProfileRepo_0 extends _i1.SmartFake
    implements _i2.EditProfileRepo {
  _FakeEditProfileRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EditProfileUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUsecase extends _i1.Mock
    implements _i3.EditProfileUsecase {
  MockEditProfileUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EditProfileRepo get editProfileRepo => (super.noSuchMethod(
        Invocation.getter(#editProfileRepo),
        returnValue: _FakeEditProfileRepo_0(
          this,
          Invocation.getter(#editProfileRepo),
        ),
      ) as _i2.EditProfileRepo);

  @override
  _i4.Future<_i5.Result<_i6.EditProfileEntity?>> editProfile(
          _i7.EditProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [request],
        ),
        returnValue: _i4.Future<_i5.Result<_i6.EditProfileEntity?>>.value(
            _i8.dummyValue<_i5.Result<_i6.EditProfileEntity?>>(
          this,
          Invocation.method(
            #editProfile,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.EditProfileEntity?>>);

  @override
  _i4.Future<_i5.Result<_i9.UpdateProfileImageResponse?>> uploadImage(
          _i10.UploadImageRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [request],
        ),
        returnValue:
            _i4.Future<_i5.Result<_i9.UpdateProfileImageResponse?>>.value(
                _i8.dummyValue<_i5.Result<_i9.UpdateProfileImageResponse?>>(
          this,
          Invocation.method(
            #uploadImage,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i9.UpdateProfileImageResponse?>>);
}

/// A class which mocks [UserProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProvider extends _i1.Mock implements _i11.UserProvider {
  MockUserProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void login(String? token) => super.noSuchMethod(
        Invocation.method(
          #login,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUser(_i12.User? user) => super.noSuchMethod(
        Invocation.method(
          #setUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logout() => super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
