// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness/test/auth/edit_profile/data/data_sources/online_data_source_impl/edit_profile_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i18;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness/core/network/api_manager.dart' as _i6;
import 'package:super_fitness/core/network/upload_image_api_manager.dart'
    as _i16;
import 'package:super_fitness/features/auth/login/data/models/request/login_request.dart'
    as _i8;
import 'package:super_fitness/features/auth/login/data/models/response/login_response.dart'
    as _i2;
import 'package:super_fitness/features/auth/register/data/models/request/register_request.dart'
    as _i13;
import 'package:super_fitness/features/auth/register/data/models/response/register_response/register_response.dart'
    as _i12;
import 'package:super_fitness/features/edit_profile/data/models/request/edit_profile_request.dart'
    as _i15;
import 'package:super_fitness/features/edit_profile/data/models/response/edit_profile_response/edit_profile_response.dart'
    as _i14;
import 'package:super_fitness/features/edit_profile/data/models/response/edit_profile_response/upload_image_response.dart'
    as _i17;
import 'package:super_fitness/features/forget_password/data/models/requests/create_newpass_request.dart'
    as _i11;
import 'package:super_fitness/features/forget_password/data/models/requests/forgot_password_request.dart'
    as _i9;
import 'package:super_fitness/features/forget_password/data/models/requests/otp_verify_reset_code_request.dart'
    as _i10;
import 'package:super_fitness/features/forget_password/data/models/responses/Create_new_pass_respones.dart'
    as _i5;
import 'package:super_fitness/features/forget_password/data/models/responses/forgot_password_response.dart'
    as _i3;
import 'package:super_fitness/features/forget_password/data/models/responses/Otp_verfication_response.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgotPasswordResponse_1 extends _i1.SmartFake
    implements _i3.ForgotPasswordResponse {
  _FakeForgotPasswordResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOtpVerifyResetCodeResponse_2 extends _i1.SmartFake
    implements _i4.OtpVerifyResetCodeResponse {
  _FakeOtpVerifyResetCodeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateNewPassResponse_3 extends _i1.SmartFake
    implements _i5.CreateNewPassResponse {
  _FakeCreateNewPassResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i6.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.LoginResponse> login(_i8.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i7.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.LoginResponse>);

  @override
  _i7.Future<_i3.ForgotPasswordResponse> forgotPassword(
          _i9.ForgotPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [request],
        ),
        returnValue: _i7.Future<_i3.ForgotPasswordResponse>.value(
            _FakeForgotPasswordResponse_1(
          this,
          Invocation.method(
            #forgotPassword,
            [request],
          ),
        )),
      ) as _i7.Future<_i3.ForgotPasswordResponse>);

  @override
  _i7.Future<_i4.OtpVerifyResetCodeResponse> resetCode(
          _i10.OtpVerifyResetCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetCode,
          [request],
        ),
        returnValue: _i7.Future<_i4.OtpVerifyResetCodeResponse>.value(
            _FakeOtpVerifyResetCodeResponse_2(
          this,
          Invocation.method(
            #resetCode,
            [request],
          ),
        )),
      ) as _i7.Future<_i4.OtpVerifyResetCodeResponse>);

  @override
  _i7.Future<_i5.CreateNewPassResponse> createNewPassword(
          _i11.CreateNewPassWordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewPassword,
          [request],
        ),
        returnValue: _i7.Future<_i5.CreateNewPassResponse>.value(
            _FakeCreateNewPassResponse_3(
          this,
          Invocation.method(
            #createNewPassword,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.CreateNewPassResponse>);

  @override
  _i7.Future<_i12.RegisterResponse?> register(_i13.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i7.Future<_i12.RegisterResponse?>.value(),
      ) as _i7.Future<_i12.RegisterResponse?>);

  @override
  _i7.Future<_i14.EditProfileResponse?> editProfile(
          _i15.EditProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [request],
        ),
        returnValue: _i7.Future<_i14.EditProfileResponse?>.value(),
      ) as _i7.Future<_i14.EditProfileResponse?>);
}

/// A class which mocks [UploadImageApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadImageApiManager extends _i1.Mock
    implements _i16.UploadImageApiManager {
  MockUploadImageApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i17.UpdateProfileImageResponse?> uploadImage(_i18.File? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [image],
        ),
        returnValue: _i7.Future<_i17.UpdateProfileImageResponse?>.value(),
      ) as _i7.Future<_i17.UpdateProfileImageResponse?>);
}
